-- for FastApi App
-- https://github.com/pgvector/pgvector?tab=readme-ov-file
-- CREATE EXTENSION vector;
-- identities
CREATE TABLE myclassmate."identities" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "user_id" BIGINT NOT NULL,
  "file_name" VARCHAR(100) NOT NULL,
  "embedding" vector(512) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX ON myclassmate."identities" USING hnsw (embedding vector_l2_ops);

-- for Spring Boot App
-- users
CREATE TABLE myclassmate."users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "username" VARCHAR(50) UNIQUE NOT NULL,
  "password" VARCHAR(255) NOT NULL,
  "name_th" VARCHAR(100) NOT NULL,
  "surname_th" VARCHAR(100) NOT NULL,
  "name_en" VARCHAR(100) NOT NULL,
  "surname_en" VARCHAR(100) NOT NULL,
  "email" VARCHAR(100) UNIQUE NOT NULL,
  "role" VARCHAR(10) NOT NULL,
  "is_deleted" BOOLEAN NOT NULL,
  "created_at" TIMESTAMP NOT NULL,
  "updated_at" TIMESTAMP NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "users_index_0" ON myclassmate."users" ("username");

CREATE INDEX "users_index_1" ON myclassmate."users" ("email");

CREATE INDEX "users_index_2" ON myclassmate."users" ("role");

-- enrollments
CREATE TABLE myclassmate."enrollments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "student_id" BIGINT NOT NULL,
  "course_id" BIGINT NOT NULL,
  "created_at" TIMESTAMP NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "enrollments_index_0" ON myclassmate."enrollments" ("student_id");

CREATE INDEX "enrollments_index_1" ON myclassmate."enrollments" ("course_id");

-- courses
CREATE TABLE myclassmate."courses" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "course_code" VARCHAR(20) UNIQUE NOT NULL,
  "course_name" VARCHAR(255) UNIQUE NOT NULL,
  "academic_year" INTEGER NOT NULL,
  "semester" INTEGER NOT NULL,
  "room" VARCHAR(20) NOT NULL,
  "start_time" TIME NOT NULL,
  "end_time" TIME NOT NULL,
  "day_of_week" VARCHAR(10) NOT NULL,
  "start_date" DATE NOT NULL,
  "end_date" DATE NOT NULL,
  "created_by" BIGINT NOT NULL,
  "created_at" TIMESTAMP NOT NULL,
  "updated_at" TIMESTAMP NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "courses_index_0" ON myclassmate."courses" ("course_code");

CREATE INDEX "courses_index_1" ON myclassmate."courses" ("course_name");

CREATE INDEX "courses_index_2" ON myclassmate."courses" ("academic_year");

-- course_lecturers
CREATE TABLE myclassmate."course_lecturers" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "course_id" BIGINT NOT NULL,
  "lecturer_id" BIGINT NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "course_lecturers_index_0" ON myclassmate."course_lecturers" ("course_id");

CREATE INDEX "course_lecturers_index_1" ON myclassmate."course_lecturers" ("lecturer_id");

CREATE TABLE myclassmate."student_profiles" (
  "student_id" BIGINT UNIQUE NOT NULL,
  "student_no" UNIQUE VARCHAR(50) NOT NULL,
  "address" VARCHAR(255) NULL,
  "phone_number" VARCHAR(10) NULL,
  "remark" VARCHAR(255) NULL,
  "created_at" TIMESTAMP NOT NULL,
  "updated_at" TIMESTAMP NOT NULL,
  PRIMARY KEY ("student_id")
);

-- course_schedules
CREATE TABLE myclassmate."course_schedules" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "course_id" BIGINT NOT NULL,
  "schedule_date" DATE NOT NULL,
  "start_time" TIME NOT NULL,
  "end_time" TIME NOT NULL,
  "room" VARCHAR(20) NOT NULL,
  "remark" VARCHAR(255) NOT NULL,
  "created_at" TIMESTAMP NOT NULL,
  "updated_at" TIMESTAMP NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "course_schedules_index_0" ON myclassmate."course_schedules" ("course_id");

-- attendances
CREATE TABLE myclassmate."attendances" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "student_id" BIGINT NOT NULL,
  "course_id" BIGINT NOT NULL,
  "course_schedule_id" BIGINT NOT NULL,
  "created_at" TIMESTAMP NOT NULL,
  "status" VARCHAR(10) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "attendances_index_0" ON myclassmate."attendances" ("student_id");

CREATE INDEX "attendances_index_1" ON myclassmate."attendances" ("course_id");

CREATE INDEX "attendances_index_2" ON myclassmate."attendances" ("course_schedule_id");

-- participations
CREATE TABLE myclassmate."participations" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "course_schedule_id" BIGINT NOT NULL,
  "round" INTEGER NOT NULL,
  "topic" VARCHAR(255) NOT NULL,
  "status" VARCHAR(10) NOT NULL,
  "created_by" BIGINT NOT NULL,
  "created_at" TIMESTAMP NOT NULL,
  "closed_at" TIMESTAMP NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "participations_index_0" ON myclassmate."participations" ("course_schedule_id");

CREATE INDEX "participations_index_1" ON myclassmate."participations" ("status");

-- participation_requests
CREATE TABLE myclassmate."participation_requests" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "participation_id" BIGINT NOT NULL,
  "student_id" BIGINT NOT NULL,
  "created_at" TIMESTAMP NOT NULL,
  "is_scored" BOOLEAN NOT NULL,
  "score" INTEGER NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "participation_requests_index_0" ON myclassmate."participation_requests" ("participation_id");

CREATE INDEX "participation_requests_index_1" ON myclassmate."participation_requests" ("student_id");

-- attendance_summaries
CREATE TABLE myclassmate."attendance_summaries" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "student_id" BIGINT NOT NULL,
  "course_id" BIGINT NOT NULL,
  "total_present" INTEGER NOT NULL,
  "total_late" INTEGER NOT NULL,
  "total_absent" INTEGER NOT NULL,
  "created_at" TIMESTAMP NOT NULL,
  "updated_at" TIMESTAMP NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "attendance_summaries_index_0" ON myclassmate."attendance_summaries" ("student_id");

CREATE INDEX "attendance_summaries_index_1" ON myclassmate."attendance_summaries" ("course_id");
